// <auto-generated />
namespace MyWinFormProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBinitializer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBinitializer));
        
        string IMigrationMetadata.Id
        {
            get { return "202208291335446_DBinitializer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
